require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LuxeRegistriesController do

  # This should return the minimal set of attributes required to create a valid
  # LuxeRegistry. As you add validations to LuxeRegistry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "event" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LuxeRegistriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all luxe_registries as @luxe_registries" do
      luxe_registry = LuxeRegistry.create! valid_attributes
      get :index, {}, valid_session
      assigns(:luxe_registries).should eq([luxe_registry])
    end
  end

  describe "GET show" do
    it "assigns the requested luxe_registry as @luxe_registry" do
      luxe_registry = LuxeRegistry.create! valid_attributes
      get :show, {:id => luxe_registry.to_param}, valid_session
      assigns(:luxe_registry).should eq(luxe_registry)
    end
  end

  describe "GET new" do
    it "assigns a new luxe_registry as @luxe_registry" do
      get :new, {}, valid_session
      assigns(:luxe_registry).should be_a_new(LuxeRegistry)
    end
  end

  describe "GET edit" do
    it "assigns the requested luxe_registry as @luxe_registry" do
      luxe_registry = LuxeRegistry.create! valid_attributes
      get :edit, {:id => luxe_registry.to_param}, valid_session
      assigns(:luxe_registry).should eq(luxe_registry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LuxeRegistry" do
        expect {
          post :create, {:luxe_registry => valid_attributes}, valid_session
        }.to change(LuxeRegistry, :count).by(1)
      end

      it "assigns a newly created luxe_registry as @luxe_registry" do
        post :create, {:luxe_registry => valid_attributes}, valid_session
        assigns(:luxe_registry).should be_a(LuxeRegistry)
        assigns(:luxe_registry).should be_persisted
      end

      it "redirects to the created luxe_registry" do
        post :create, {:luxe_registry => valid_attributes}, valid_session
        response.should redirect_to(LuxeRegistry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved luxe_registry as @luxe_registry" do
        # Trigger the behavior that occurs when invalid params are submitted
        LuxeRegistry.any_instance.stub(:save).and_return(false)
        post :create, {:luxe_registry => { "event" => "invalid value" }}, valid_session
        assigns(:luxe_registry).should be_a_new(LuxeRegistry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LuxeRegistry.any_instance.stub(:save).and_return(false)
        post :create, {:luxe_registry => { "event" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested luxe_registry" do
        luxe_registry = LuxeRegistry.create! valid_attributes
        # Assuming there are no other luxe_registries in the database, this
        # specifies that the LuxeRegistry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LuxeRegistry.any_instance.should_receive(:update_attributes).with({ "event" => "" })
        put :update, {:id => luxe_registry.to_param, :luxe_registry => { "event" => "" }}, valid_session
      end

      it "assigns the requested luxe_registry as @luxe_registry" do
        luxe_registry = LuxeRegistry.create! valid_attributes
        put :update, {:id => luxe_registry.to_param, :luxe_registry => valid_attributes}, valid_session
        assigns(:luxe_registry).should eq(luxe_registry)
      end

      it "redirects to the luxe_registry" do
        luxe_registry = LuxeRegistry.create! valid_attributes
        put :update, {:id => luxe_registry.to_param, :luxe_registry => valid_attributes}, valid_session
        response.should redirect_to(luxe_registry)
      end
    end

    describe "with invalid params" do
      it "assigns the luxe_registry as @luxe_registry" do
        luxe_registry = LuxeRegistry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LuxeRegistry.any_instance.stub(:save).and_return(false)
        put :update, {:id => luxe_registry.to_param, :luxe_registry => { "event" => "invalid value" }}, valid_session
        assigns(:luxe_registry).should eq(luxe_registry)
      end

      it "re-renders the 'edit' template" do
        luxe_registry = LuxeRegistry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LuxeRegistry.any_instance.stub(:save).and_return(false)
        put :update, {:id => luxe_registry.to_param, :luxe_registry => { "event" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested luxe_registry" do
      luxe_registry = LuxeRegistry.create! valid_attributes
      expect {
        delete :destroy, {:id => luxe_registry.to_param}, valid_session
      }.to change(LuxeRegistry, :count).by(-1)
    end

    it "redirects to the luxe_registries list" do
      luxe_registry = LuxeRegistry.create! valid_attributes
      delete :destroy, {:id => luxe_registry.to_param}, valid_session
      response.should redirect_to(luxe_registries_url)
    end
  end

end
